/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRouteImport } from './routes/track'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CreateRequestRouteImport } from './routes/create-request'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as AppTransmittedRouteImport } from './routes/app.transmitted'
import { Route as AppSupervisionRouteImport } from './routes/app.supervision'
import { Route as AppSlaCenterRouteImport } from './routes/app.sla-center'
import { Route as AppResolvedRouteImport } from './routes/app.resolved'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppQueueRouteImport } from './routes/app.queue'
import { Route as AppPvTrackingRouteImport } from './routes/app.pv-tracking'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppNewRouteImport } from './routes/app.new'
import { Route as AppMyTicketsRouteImport } from './routes/app.my-tickets'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppDistributionRouteImport } from './routes/app.distribution'
import { Route as AppDgRouteImport } from './routes/app.dg'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppRequestsIndexRouteImport } from './routes/app.requests.index'
import { Route as AppRequestsHistoryRouteImport } from './routes/app.requests.history'
import { Route as AppRequestsIdRouteImport } from './routes/app.requests.$id'
import { Route as AppAdminUsersRouteImport } from './routes/app.admin.users'
import { Route as AppAdminUnitsRouteImport } from './routes/app.admin.units'
import { Route as AppAdminTicketTraceRouteImport } from './routes/app.admin.ticket-trace'
import { Route as AppAdminSlaRouteImport } from './routes/app.admin.sla'
import { Route as AppAdminRoutingRouteImport } from './routes/app.admin.routing'
import { Route as AppAdminReferencesRouteImport } from './routes/app.admin.references'
import { Route as AppAdminPrioritiesRouteImport } from './routes/app.admin.priorities'
import { Route as AppAdminOrgRouteImport } from './routes/app.admin.org'
import { Route as AppAdminLogsRouteImport } from './routes/app.admin.logs'
import { Route as AppAdminHomepageRouteImport } from './routes/app.admin.homepage'
import { Route as AppAdminDirectionsRouteImport } from './routes/app.admin.directions'
import { Route as AppAdminDepartmentsRouteImport } from './routes/app.admin.departments'
import { Route as AppAdminAuditRouteImport } from './routes/app.admin.audit'
import { Route as AppTransmittedTicketsIdRouteImport } from './routes/app.transmitted_.tickets.$id'
import { Route as AppSupervisionTicketsIdRouteImport } from './routes/app.supervision_.tickets.$id'
import { Route as AppSlaCenterTicketsIdRouteImport } from './routes/app.sla-center_.tickets.$id'
import { Route as AppResolvedTicketsIdRouteImport } from './routes/app.resolved_.tickets.$id'
import { Route as AppQueueTicketsIdRouteImport } from './routes/app.queue_.tickets.$id'
import { Route as AppMyTicketsTicketsIdRouteImport } from './routes/app.my-tickets_.tickets.$id'
import { Route as AppHistoryTicketsIdRouteImport } from './routes/app.history_.tickets.$id'
import { Route as AppDistributionTicketsIdRouteImport } from './routes/app.distribution_.tickets.$id'
import { Route as AppDgTicketsIdRouteImport } from './routes/app.dg_.tickets.$id'
import { Route as AppAdminTicketsIdRouteImport } from './routes/app.admin.tickets.$id'
import { Route as AppAdminDirectionsIdRouteImport } from './routes/app.admin.directions.$id'

const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRequestRoute = CreateRequestRouteImport.update({
  id: '/create-request',
  path: '/create-request',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTransmittedRoute = AppTransmittedRouteImport.update({
  id: '/transmitted',
  path: '/transmitted',
  getParentRoute: () => AppRoute,
} as any)
const AppSupervisionRoute = AppSupervisionRouteImport.update({
  id: '/supervision',
  path: '/supervision',
  getParentRoute: () => AppRoute,
} as any)
const AppSlaCenterRoute = AppSlaCenterRouteImport.update({
  id: '/sla-center',
  path: '/sla-center',
  getParentRoute: () => AppRoute,
} as any)
const AppResolvedRoute = AppResolvedRouteImport.update({
  id: '/resolved',
  path: '/resolved',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppQueueRoute = AppQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AppRoute,
} as any)
const AppPvTrackingRoute = AppPvTrackingRouteImport.update({
  id: '/pv-tracking',
  path: '/pv-tracking',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppNewRoute = AppNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppRoute,
} as any)
const AppMyTicketsRoute = AppMyTicketsRouteImport.update({
  id: '/my-tickets',
  path: '/my-tickets',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppDistributionRoute = AppDistributionRouteImport.update({
  id: '/distribution',
  path: '/distribution',
  getParentRoute: () => AppRoute,
} as any)
const AppDgRoute = AppDgRouteImport.update({
  id: '/dg',
  path: '/dg',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestsIndexRoute = AppRequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestsHistoryRoute = AppRequestsHistoryRouteImport.update({
  id: '/requests/history',
  path: '/requests/history',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestsIdRoute = AppRequestsIdRouteImport.update({
  id: '/requests/$id',
  path: '/requests/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminUnitsRoute = AppAdminUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminTicketTraceRoute = AppAdminTicketTraceRouteImport.update({
  id: '/ticket-trace',
  path: '/ticket-trace',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminSlaRoute = AppAdminSlaRouteImport.update({
  id: '/sla',
  path: '/sla',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminRoutingRoute = AppAdminRoutingRouteImport.update({
  id: '/routing',
  path: '/routing',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminReferencesRoute = AppAdminReferencesRouteImport.update({
  id: '/references',
  path: '/references',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminPrioritiesRoute = AppAdminPrioritiesRouteImport.update({
  id: '/priorities',
  path: '/priorities',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminOrgRoute = AppAdminOrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminLogsRoute = AppAdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminHomepageRoute = AppAdminHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminDirectionsRoute = AppAdminDirectionsRouteImport.update({
  id: '/directions',
  path: '/directions',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminDepartmentsRoute = AppAdminDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAuditRoute = AppAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppTransmittedTicketsIdRoute = AppTransmittedTicketsIdRouteImport.update({
  id: '/transmitted_/tickets/$id',
  path: '/transmitted/tickets/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSupervisionTicketsIdRoute = AppSupervisionTicketsIdRouteImport.update({
  id: '/supervision_/tickets/$id',
  path: '/supervision/tickets/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSlaCenterTicketsIdRoute = AppSlaCenterTicketsIdRouteImport.update({
  id: '/sla-center_/tickets/$id',
  path: '/sla-center/tickets/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppResolvedTicketsIdRoute = AppResolvedTicketsIdRouteImport.update({
  id: '/resolved_/tickets/$id',
  path: '/resolved/tickets/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppQueueTicketsIdRoute = AppQueueTicketsIdRouteImport.update({
  id: '/queue_/tickets/$id',
  path: '/queue/tickets/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppMyTicketsTicketsIdRoute = AppMyTicketsTicketsIdRouteImport.update({
  id: '/my-tickets_/tickets/$id',
  path: '/my-tickets/tickets/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryTicketsIdRoute = AppHistoryTicketsIdRouteImport.update({
  id: '/history_/tickets/$id',
  path: '/history/tickets/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppDistributionTicketsIdRoute =
  AppDistributionTicketsIdRouteImport.update({
    id: '/distribution_/tickets/$id',
    path: '/distribution/tickets/$id',
    getParentRoute: () => AppRoute,
  } as any)
const AppDgTicketsIdRoute = AppDgTicketsIdRouteImport.update({
  id: '/dg_/tickets/$id',
  path: '/dg/tickets/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminTicketsIdRoute = AppAdminTicketsIdRouteImport.update({
  id: '/tickets/$id',
  path: '/tickets/$id',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminDirectionsIdRoute = AppAdminDirectionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAdminDirectionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/app': typeof AppRouteWithChildren
  '/consent': typeof ConsentRoute
  '/create-request': typeof CreateRequestRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/track': typeof TrackRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/dg': typeof AppDgRoute
  '/app/distribution': typeof AppDistributionRoute
  '/app/history': typeof AppHistoryRoute
  '/app/my-tickets': typeof AppMyTicketsRoute
  '/app/new': typeof AppNewRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/pv-tracking': typeof AppPvTrackingRoute
  '/app/queue': typeof AppQueueRoute
  '/app/reports': typeof AppReportsRoute
  '/app/resolved': typeof AppResolvedRoute
  '/app/sla-center': typeof AppSlaCenterRoute
  '/app/supervision': typeof AppSupervisionRoute
  '/app/transmitted': typeof AppTransmittedRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/audit': typeof AppAdminAuditRoute
  '/app/admin/departments': typeof AppAdminDepartmentsRoute
  '/app/admin/directions': typeof AppAdminDirectionsRouteWithChildren
  '/app/admin/homepage': typeof AppAdminHomepageRoute
  '/app/admin/logs': typeof AppAdminLogsRoute
  '/app/admin/org': typeof AppAdminOrgRoute
  '/app/admin/priorities': typeof AppAdminPrioritiesRoute
  '/app/admin/references': typeof AppAdminReferencesRoute
  '/app/admin/routing': typeof AppAdminRoutingRoute
  '/app/admin/sla': typeof AppAdminSlaRoute
  '/app/admin/ticket-trace': typeof AppAdminTicketTraceRoute
  '/app/admin/units': typeof AppAdminUnitsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/requests/$id': typeof AppRequestsIdRoute
  '/app/requests/history': typeof AppRequestsHistoryRoute
  '/app/requests/': typeof AppRequestsIndexRoute
  '/app/admin/directions/$id': typeof AppAdminDirectionsIdRoute
  '/app/admin/tickets/$id': typeof AppAdminTicketsIdRoute
  '/app/dg/tickets/$id': typeof AppDgTicketsIdRoute
  '/app/distribution/tickets/$id': typeof AppDistributionTicketsIdRoute
  '/app/history/tickets/$id': typeof AppHistoryTicketsIdRoute
  '/app/my-tickets/tickets/$id': typeof AppMyTicketsTicketsIdRoute
  '/app/queue/tickets/$id': typeof AppQueueTicketsIdRoute
  '/app/resolved/tickets/$id': typeof AppResolvedTicketsIdRoute
  '/app/sla-center/tickets/$id': typeof AppSlaCenterTicketsIdRoute
  '/app/supervision/tickets/$id': typeof AppSupervisionTicketsIdRoute
  '/app/transmitted/tickets/$id': typeof AppTransmittedTicketsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/consent': typeof ConsentRoute
  '/create-request': typeof CreateRequestRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/track': typeof TrackRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/dg': typeof AppDgRoute
  '/app/distribution': typeof AppDistributionRoute
  '/app/history': typeof AppHistoryRoute
  '/app/my-tickets': typeof AppMyTicketsRoute
  '/app/new': typeof AppNewRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/pv-tracking': typeof AppPvTrackingRoute
  '/app/queue': typeof AppQueueRoute
  '/app/reports': typeof AppReportsRoute
  '/app/resolved': typeof AppResolvedRoute
  '/app/sla-center': typeof AppSlaCenterRoute
  '/app/supervision': typeof AppSupervisionRoute
  '/app/transmitted': typeof AppTransmittedRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/app': typeof AppIndexRoute
  '/app/admin/audit': typeof AppAdminAuditRoute
  '/app/admin/departments': typeof AppAdminDepartmentsRoute
  '/app/admin/directions': typeof AppAdminDirectionsRouteWithChildren
  '/app/admin/homepage': typeof AppAdminHomepageRoute
  '/app/admin/logs': typeof AppAdminLogsRoute
  '/app/admin/org': typeof AppAdminOrgRoute
  '/app/admin/priorities': typeof AppAdminPrioritiesRoute
  '/app/admin/references': typeof AppAdminReferencesRoute
  '/app/admin/routing': typeof AppAdminRoutingRoute
  '/app/admin/sla': typeof AppAdminSlaRoute
  '/app/admin/ticket-trace': typeof AppAdminTicketTraceRoute
  '/app/admin/units': typeof AppAdminUnitsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/requests/$id': typeof AppRequestsIdRoute
  '/app/requests/history': typeof AppRequestsHistoryRoute
  '/app/requests': typeof AppRequestsIndexRoute
  '/app/admin/directions/$id': typeof AppAdminDirectionsIdRoute
  '/app/admin/tickets/$id': typeof AppAdminTicketsIdRoute
  '/app/dg/tickets/$id': typeof AppDgTicketsIdRoute
  '/app/distribution/tickets/$id': typeof AppDistributionTicketsIdRoute
  '/app/history/tickets/$id': typeof AppHistoryTicketsIdRoute
  '/app/my-tickets/tickets/$id': typeof AppMyTicketsTicketsIdRoute
  '/app/queue/tickets/$id': typeof AppQueueTicketsIdRoute
  '/app/resolved/tickets/$id': typeof AppResolvedTicketsIdRoute
  '/app/sla-center/tickets/$id': typeof AppSlaCenterTicketsIdRoute
  '/app/supervision/tickets/$id': typeof AppSupervisionTicketsIdRoute
  '/app/transmitted/tickets/$id': typeof AppTransmittedTicketsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/app': typeof AppRouteWithChildren
  '/consent': typeof ConsentRoute
  '/create-request': typeof CreateRequestRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/track': typeof TrackRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/dg': typeof AppDgRoute
  '/app/distribution': typeof AppDistributionRoute
  '/app/history': typeof AppHistoryRoute
  '/app/my-tickets': typeof AppMyTicketsRoute
  '/app/new': typeof AppNewRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/pv-tracking': typeof AppPvTrackingRoute
  '/app/queue': typeof AppQueueRoute
  '/app/reports': typeof AppReportsRoute
  '/app/resolved': typeof AppResolvedRoute
  '/app/sla-center': typeof AppSlaCenterRoute
  '/app/supervision': typeof AppSupervisionRoute
  '/app/transmitted': typeof AppTransmittedRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/audit': typeof AppAdminAuditRoute
  '/app/admin/departments': typeof AppAdminDepartmentsRoute
  '/app/admin/directions': typeof AppAdminDirectionsRouteWithChildren
  '/app/admin/homepage': typeof AppAdminHomepageRoute
  '/app/admin/logs': typeof AppAdminLogsRoute
  '/app/admin/org': typeof AppAdminOrgRoute
  '/app/admin/priorities': typeof AppAdminPrioritiesRoute
  '/app/admin/references': typeof AppAdminReferencesRoute
  '/app/admin/routing': typeof AppAdminRoutingRoute
  '/app/admin/sla': typeof AppAdminSlaRoute
  '/app/admin/ticket-trace': typeof AppAdminTicketTraceRoute
  '/app/admin/units': typeof AppAdminUnitsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/requests/$id': typeof AppRequestsIdRoute
  '/app/requests/history': typeof AppRequestsHistoryRoute
  '/app/requests/': typeof AppRequestsIndexRoute
  '/app/admin/directions/$id': typeof AppAdminDirectionsIdRoute
  '/app/admin/tickets/$id': typeof AppAdminTicketsIdRoute
  '/app/dg_/tickets/$id': typeof AppDgTicketsIdRoute
  '/app/distribution_/tickets/$id': typeof AppDistributionTicketsIdRoute
  '/app/history_/tickets/$id': typeof AppHistoryTicketsIdRoute
  '/app/my-tickets_/tickets/$id': typeof AppMyTicketsTicketsIdRoute
  '/app/queue_/tickets/$id': typeof AppQueueTicketsIdRoute
  '/app/resolved_/tickets/$id': typeof AppResolvedTicketsIdRoute
  '/app/sla-center_/tickets/$id': typeof AppSlaCenterTicketsIdRoute
  '/app/supervision_/tickets/$id': typeof AppSupervisionTicketsIdRoute
  '/app/transmitted_/tickets/$id': typeof AppTransmittedTicketsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-login'
    | '/app'
    | '/consent'
    | '/create-request'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/track'
    | '/app/admin'
    | '/app/dg'
    | '/app/distribution'
    | '/app/history'
    | '/app/my-tickets'
    | '/app/new'
    | '/app/notifications'
    | '/app/profile'
    | '/app/pv-tracking'
    | '/app/queue'
    | '/app/reports'
    | '/app/resolved'
    | '/app/sla-center'
    | '/app/supervision'
    | '/app/transmitted'
    | '/legal/privacy'
    | '/legal/terms'
    | '/app/'
    | '/app/admin/audit'
    | '/app/admin/departments'
    | '/app/admin/directions'
    | '/app/admin/homepage'
    | '/app/admin/logs'
    | '/app/admin/org'
    | '/app/admin/priorities'
    | '/app/admin/references'
    | '/app/admin/routing'
    | '/app/admin/sla'
    | '/app/admin/ticket-trace'
    | '/app/admin/units'
    | '/app/admin/users'
    | '/app/requests/$id'
    | '/app/requests/history'
    | '/app/requests/'
    | '/app/admin/directions/$id'
    | '/app/admin/tickets/$id'
    | '/app/dg/tickets/$id'
    | '/app/distribution/tickets/$id'
    | '/app/history/tickets/$id'
    | '/app/my-tickets/tickets/$id'
    | '/app/queue/tickets/$id'
    | '/app/resolved/tickets/$id'
    | '/app/sla-center/tickets/$id'
    | '/app/supervision/tickets/$id'
    | '/app/transmitted/tickets/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/consent'
    | '/create-request'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/track'
    | '/app/admin'
    | '/app/dg'
    | '/app/distribution'
    | '/app/history'
    | '/app/my-tickets'
    | '/app/new'
    | '/app/notifications'
    | '/app/profile'
    | '/app/pv-tracking'
    | '/app/queue'
    | '/app/reports'
    | '/app/resolved'
    | '/app/sla-center'
    | '/app/supervision'
    | '/app/transmitted'
    | '/legal/privacy'
    | '/legal/terms'
    | '/app'
    | '/app/admin/audit'
    | '/app/admin/departments'
    | '/app/admin/directions'
    | '/app/admin/homepage'
    | '/app/admin/logs'
    | '/app/admin/org'
    | '/app/admin/priorities'
    | '/app/admin/references'
    | '/app/admin/routing'
    | '/app/admin/sla'
    | '/app/admin/ticket-trace'
    | '/app/admin/units'
    | '/app/admin/users'
    | '/app/requests/$id'
    | '/app/requests/history'
    | '/app/requests'
    | '/app/admin/directions/$id'
    | '/app/admin/tickets/$id'
    | '/app/dg/tickets/$id'
    | '/app/distribution/tickets/$id'
    | '/app/history/tickets/$id'
    | '/app/my-tickets/tickets/$id'
    | '/app/queue/tickets/$id'
    | '/app/resolved/tickets/$id'
    | '/app/sla-center/tickets/$id'
    | '/app/supervision/tickets/$id'
    | '/app/transmitted/tickets/$id'
  id:
    | '__root__'
    | '/'
    | '/admin-login'
    | '/app'
    | '/consent'
    | '/create-request'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/track'
    | '/app/admin'
    | '/app/dg'
    | '/app/distribution'
    | '/app/history'
    | '/app/my-tickets'
    | '/app/new'
    | '/app/notifications'
    | '/app/profile'
    | '/app/pv-tracking'
    | '/app/queue'
    | '/app/reports'
    | '/app/resolved'
    | '/app/sla-center'
    | '/app/supervision'
    | '/app/transmitted'
    | '/legal/privacy'
    | '/legal/terms'
    | '/app/'
    | '/app/admin/audit'
    | '/app/admin/departments'
    | '/app/admin/directions'
    | '/app/admin/homepage'
    | '/app/admin/logs'
    | '/app/admin/org'
    | '/app/admin/priorities'
    | '/app/admin/references'
    | '/app/admin/routing'
    | '/app/admin/sla'
    | '/app/admin/ticket-trace'
    | '/app/admin/units'
    | '/app/admin/users'
    | '/app/requests/$id'
    | '/app/requests/history'
    | '/app/requests/'
    | '/app/admin/directions/$id'
    | '/app/admin/tickets/$id'
    | '/app/dg_/tickets/$id'
    | '/app/distribution_/tickets/$id'
    | '/app/history_/tickets/$id'
    | '/app/my-tickets_/tickets/$id'
    | '/app/queue_/tickets/$id'
    | '/app/resolved_/tickets/$id'
    | '/app/sla-center_/tickets/$id'
    | '/app/supervision_/tickets/$id'
    | '/app/transmitted_/tickets/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AppRoute: typeof AppRouteWithChildren
  ConsentRoute: typeof ConsentRoute
  CreateRequestRoute: typeof CreateRequestRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  TrackRoute: typeof TrackRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-request': {
      id: '/create-request'
      path: '/create-request'
      fullPath: '/create-request'
      preLoaderRoute: typeof CreateRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/transmitted': {
      id: '/app/transmitted'
      path: '/transmitted'
      fullPath: '/app/transmitted'
      preLoaderRoute: typeof AppTransmittedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/supervision': {
      id: '/app/supervision'
      path: '/supervision'
      fullPath: '/app/supervision'
      preLoaderRoute: typeof AppSupervisionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sla-center': {
      id: '/app/sla-center'
      path: '/sla-center'
      fullPath: '/app/sla-center'
      preLoaderRoute: typeof AppSlaCenterRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/resolved': {
      id: '/app/resolved'
      path: '/resolved'
      fullPath: '/app/resolved'
      preLoaderRoute: typeof AppResolvedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/queue': {
      id: '/app/queue'
      path: '/queue'
      fullPath: '/app/queue'
      preLoaderRoute: typeof AppQueueRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pv-tracking': {
      id: '/app/pv-tracking'
      path: '/pv-tracking'
      fullPath: '/app/pv-tracking'
      preLoaderRoute: typeof AppPvTrackingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/new': {
      id: '/app/new'
      path: '/new'
      fullPath: '/app/new'
      preLoaderRoute: typeof AppNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/my-tickets': {
      id: '/app/my-tickets'
      path: '/my-tickets'
      fullPath: '/app/my-tickets'
      preLoaderRoute: typeof AppMyTicketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/distribution': {
      id: '/app/distribution'
      path: '/distribution'
      fullPath: '/app/distribution'
      preLoaderRoute: typeof AppDistributionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dg': {
      id: '/app/dg'
      path: '/dg'
      fullPath: '/app/dg'
      preLoaderRoute: typeof AppDgRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/requests/': {
      id: '/app/requests/'
      path: '/requests'
      fullPath: '/app/requests/'
      preLoaderRoute: typeof AppRequestsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/requests/history': {
      id: '/app/requests/history'
      path: '/requests/history'
      fullPath: '/app/requests/history'
      preLoaderRoute: typeof AppRequestsHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/requests/$id': {
      id: '/app/requests/$id'
      path: '/requests/$id'
      fullPath: '/app/requests/$id'
      preLoaderRoute: typeof AppRequestsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/units': {
      id: '/app/admin/units'
      path: '/units'
      fullPath: '/app/admin/units'
      preLoaderRoute: typeof AppAdminUnitsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/ticket-trace': {
      id: '/app/admin/ticket-trace'
      path: '/ticket-trace'
      fullPath: '/app/admin/ticket-trace'
      preLoaderRoute: typeof AppAdminTicketTraceRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/sla': {
      id: '/app/admin/sla'
      path: '/sla'
      fullPath: '/app/admin/sla'
      preLoaderRoute: typeof AppAdminSlaRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/routing': {
      id: '/app/admin/routing'
      path: '/routing'
      fullPath: '/app/admin/routing'
      preLoaderRoute: typeof AppAdminRoutingRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/references': {
      id: '/app/admin/references'
      path: '/references'
      fullPath: '/app/admin/references'
      preLoaderRoute: typeof AppAdminReferencesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/priorities': {
      id: '/app/admin/priorities'
      path: '/priorities'
      fullPath: '/app/admin/priorities'
      preLoaderRoute: typeof AppAdminPrioritiesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/org': {
      id: '/app/admin/org'
      path: '/org'
      fullPath: '/app/admin/org'
      preLoaderRoute: typeof AppAdminOrgRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/logs': {
      id: '/app/admin/logs'
      path: '/logs'
      fullPath: '/app/admin/logs'
      preLoaderRoute: typeof AppAdminLogsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/homepage': {
      id: '/app/admin/homepage'
      path: '/homepage'
      fullPath: '/app/admin/homepage'
      preLoaderRoute: typeof AppAdminHomepageRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/directions': {
      id: '/app/admin/directions'
      path: '/directions'
      fullPath: '/app/admin/directions'
      preLoaderRoute: typeof AppAdminDirectionsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/departments': {
      id: '/app/admin/departments'
      path: '/departments'
      fullPath: '/app/admin/departments'
      preLoaderRoute: typeof AppAdminDepartmentsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/audit': {
      id: '/app/admin/audit'
      path: '/audit'
      fullPath: '/app/admin/audit'
      preLoaderRoute: typeof AppAdminAuditRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/transmitted_/tickets/$id': {
      id: '/app/transmitted_/tickets/$id'
      path: '/transmitted/tickets/$id'
      fullPath: '/app/transmitted/tickets/$id'
      preLoaderRoute: typeof AppTransmittedTicketsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/supervision_/tickets/$id': {
      id: '/app/supervision_/tickets/$id'
      path: '/supervision/tickets/$id'
      fullPath: '/app/supervision/tickets/$id'
      preLoaderRoute: typeof AppSupervisionTicketsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sla-center_/tickets/$id': {
      id: '/app/sla-center_/tickets/$id'
      path: '/sla-center/tickets/$id'
      fullPath: '/app/sla-center/tickets/$id'
      preLoaderRoute: typeof AppSlaCenterTicketsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/resolved_/tickets/$id': {
      id: '/app/resolved_/tickets/$id'
      path: '/resolved/tickets/$id'
      fullPath: '/app/resolved/tickets/$id'
      preLoaderRoute: typeof AppResolvedTicketsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/queue_/tickets/$id': {
      id: '/app/queue_/tickets/$id'
      path: '/queue/tickets/$id'
      fullPath: '/app/queue/tickets/$id'
      preLoaderRoute: typeof AppQueueTicketsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/my-tickets_/tickets/$id': {
      id: '/app/my-tickets_/tickets/$id'
      path: '/my-tickets/tickets/$id'
      fullPath: '/app/my-tickets/tickets/$id'
      preLoaderRoute: typeof AppMyTicketsTicketsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history_/tickets/$id': {
      id: '/app/history_/tickets/$id'
      path: '/history/tickets/$id'
      fullPath: '/app/history/tickets/$id'
      preLoaderRoute: typeof AppHistoryTicketsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/distribution_/tickets/$id': {
      id: '/app/distribution_/tickets/$id'
      path: '/distribution/tickets/$id'
      fullPath: '/app/distribution/tickets/$id'
      preLoaderRoute: typeof AppDistributionTicketsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dg_/tickets/$id': {
      id: '/app/dg_/tickets/$id'
      path: '/dg/tickets/$id'
      fullPath: '/app/dg/tickets/$id'
      preLoaderRoute: typeof AppDgTicketsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/tickets/$id': {
      id: '/app/admin/tickets/$id'
      path: '/tickets/$id'
      fullPath: '/app/admin/tickets/$id'
      preLoaderRoute: typeof AppAdminTicketsIdRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/directions/$id': {
      id: '/app/admin/directions/$id'
      path: '/$id'
      fullPath: '/app/admin/directions/$id'
      preLoaderRoute: typeof AppAdminDirectionsIdRouteImport
      parentRoute: typeof AppAdminDirectionsRoute
    }
  }
}

interface AppAdminDirectionsRouteChildren {
  AppAdminDirectionsIdRoute: typeof AppAdminDirectionsIdRoute
}

const AppAdminDirectionsRouteChildren: AppAdminDirectionsRouteChildren = {
  AppAdminDirectionsIdRoute: AppAdminDirectionsIdRoute,
}

const AppAdminDirectionsRouteWithChildren =
  AppAdminDirectionsRoute._addFileChildren(AppAdminDirectionsRouteChildren)

interface AppAdminRouteChildren {
  AppAdminAuditRoute: typeof AppAdminAuditRoute
  AppAdminDepartmentsRoute: typeof AppAdminDepartmentsRoute
  AppAdminDirectionsRoute: typeof AppAdminDirectionsRouteWithChildren
  AppAdminHomepageRoute: typeof AppAdminHomepageRoute
  AppAdminLogsRoute: typeof AppAdminLogsRoute
  AppAdminOrgRoute: typeof AppAdminOrgRoute
  AppAdminPrioritiesRoute: typeof AppAdminPrioritiesRoute
  AppAdminReferencesRoute: typeof AppAdminReferencesRoute
  AppAdminRoutingRoute: typeof AppAdminRoutingRoute
  AppAdminSlaRoute: typeof AppAdminSlaRoute
  AppAdminTicketTraceRoute: typeof AppAdminTicketTraceRoute
  AppAdminUnitsRoute: typeof AppAdminUnitsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAdminTicketsIdRoute: typeof AppAdminTicketsIdRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAuditRoute: AppAdminAuditRoute,
  AppAdminDepartmentsRoute: AppAdminDepartmentsRoute,
  AppAdminDirectionsRoute: AppAdminDirectionsRouteWithChildren,
  AppAdminHomepageRoute: AppAdminHomepageRoute,
  AppAdminLogsRoute: AppAdminLogsRoute,
  AppAdminOrgRoute: AppAdminOrgRoute,
  AppAdminPrioritiesRoute: AppAdminPrioritiesRoute,
  AppAdminReferencesRoute: AppAdminReferencesRoute,
  AppAdminRoutingRoute: AppAdminRoutingRoute,
  AppAdminSlaRoute: AppAdminSlaRoute,
  AppAdminTicketTraceRoute: AppAdminTicketTraceRoute,
  AppAdminUnitsRoute: AppAdminUnitsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAdminTicketsIdRoute: AppAdminTicketsIdRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppDgRoute: typeof AppDgRoute
  AppDistributionRoute: typeof AppDistributionRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppMyTicketsRoute: typeof AppMyTicketsRoute
  AppNewRoute: typeof AppNewRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppPvTrackingRoute: typeof AppPvTrackingRoute
  AppQueueRoute: typeof AppQueueRoute
  AppReportsRoute: typeof AppReportsRoute
  AppResolvedRoute: typeof AppResolvedRoute
  AppSlaCenterRoute: typeof AppSlaCenterRoute
  AppSupervisionRoute: typeof AppSupervisionRoute
  AppTransmittedRoute: typeof AppTransmittedRoute
  AppIndexRoute: typeof AppIndexRoute
  AppRequestsIdRoute: typeof AppRequestsIdRoute
  AppRequestsHistoryRoute: typeof AppRequestsHistoryRoute
  AppRequestsIndexRoute: typeof AppRequestsIndexRoute
  AppDgTicketsIdRoute: typeof AppDgTicketsIdRoute
  AppDistributionTicketsIdRoute: typeof AppDistributionTicketsIdRoute
  AppHistoryTicketsIdRoute: typeof AppHistoryTicketsIdRoute
  AppMyTicketsTicketsIdRoute: typeof AppMyTicketsTicketsIdRoute
  AppQueueTicketsIdRoute: typeof AppQueueTicketsIdRoute
  AppResolvedTicketsIdRoute: typeof AppResolvedTicketsIdRoute
  AppSlaCenterTicketsIdRoute: typeof AppSlaCenterTicketsIdRoute
  AppSupervisionTicketsIdRoute: typeof AppSupervisionTicketsIdRoute
  AppTransmittedTicketsIdRoute: typeof AppTransmittedTicketsIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppDgRoute: AppDgRoute,
  AppDistributionRoute: AppDistributionRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppMyTicketsRoute: AppMyTicketsRoute,
  AppNewRoute: AppNewRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppPvTrackingRoute: AppPvTrackingRoute,
  AppQueueRoute: AppQueueRoute,
  AppReportsRoute: AppReportsRoute,
  AppResolvedRoute: AppResolvedRoute,
  AppSlaCenterRoute: AppSlaCenterRoute,
  AppSupervisionRoute: AppSupervisionRoute,
  AppTransmittedRoute: AppTransmittedRoute,
  AppIndexRoute: AppIndexRoute,
  AppRequestsIdRoute: AppRequestsIdRoute,
  AppRequestsHistoryRoute: AppRequestsHistoryRoute,
  AppRequestsIndexRoute: AppRequestsIndexRoute,
  AppDgTicketsIdRoute: AppDgTicketsIdRoute,
  AppDistributionTicketsIdRoute: AppDistributionTicketsIdRoute,
  AppHistoryTicketsIdRoute: AppHistoryTicketsIdRoute,
  AppMyTicketsTicketsIdRoute: AppMyTicketsTicketsIdRoute,
  AppQueueTicketsIdRoute: AppQueueTicketsIdRoute,
  AppResolvedTicketsIdRoute: AppResolvedTicketsIdRoute,
  AppSlaCenterTicketsIdRoute: AppSlaCenterTicketsIdRoute,
  AppSupervisionTicketsIdRoute: AppSupervisionTicketsIdRoute,
  AppTransmittedTicketsIdRoute: AppTransmittedTicketsIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminLoginRoute: AdminLoginRoute,
  AppRoute: AppRouteWithChildren,
  ConsentRoute: ConsentRoute,
  CreateRequestRoute: CreateRequestRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  TrackRoute: TrackRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
