/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRouteImport } from './routes/track'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CreateRequestRouteImport } from './routes/create-request'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTriageRouteImport } from './routes/app.triage'
import { Route as AppSupervisionRouteImport } from './routes/app.supervision'
import { Route as AppSlaCenterRouteImport } from './routes/app.sla-center'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppQueueRouteImport } from './routes/app.queue'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppNewRouteImport } from './routes/app.new'
import { Route as AppMyTicketsRouteImport } from './routes/app.my-tickets'
import { Route as AppKnowledgeRouteImport } from './routes/app.knowledge'
import { Route as AppDirectionRouteImport } from './routes/app.direction'
import { Route as AppDgRouteImport } from './routes/app.dg'
import { Route as AppChiefInboxRouteImport } from './routes/app.chief-inbox'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppRequestsIndexRouteImport } from './routes/app.requests.index'
import { Route as AppRequestsHistoryRouteImport } from './routes/app.requests.history'
import { Route as AppRequestsIdRouteImport } from './routes/app.requests.$id'
import { Route as AppAdminUsersRouteImport } from './routes/app.admin.users'
import { Route as AppAdminUnitsRouteImport } from './routes/app.admin.units'
import { Route as AppAdminSlaRouteImport } from './routes/app.admin.sla'
import { Route as AppAdminSettingsRouteImport } from './routes/app.admin.settings'
import { Route as AppAdminSecurityRouteImport } from './routes/app.admin.security'
import { Route as AppAdminRoutingRouteImport } from './routes/app.admin.routing'
import { Route as AppAdminReferencesRouteImport } from './routes/app.admin.references'
import { Route as AppAdminPrioritiesRouteImport } from './routes/app.admin.priorities'
import { Route as AppAdminOrgRouteImport } from './routes/app.admin.org'
import { Route as AppAdminLogsRouteImport } from './routes/app.admin.logs'
import { Route as AppAdminKnowledgeRouteImport } from './routes/app.admin.knowledge'
import { Route as AppAdminHomepageRouteImport } from './routes/app.admin.homepage'
import { Route as AppAdminDirectionsRouteImport } from './routes/app.admin.directions'
import { Route as AppAdminCommunicationRouteImport } from './routes/app.admin.communication'
import { Route as AppAdminAuditRouteImport } from './routes/app.admin.audit'

const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRequestRoute = CreateRequestRouteImport.update({
  id: '/create-request',
  path: '/create-request',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTriageRoute = AppTriageRouteImport.update({
  id: '/triage',
  path: '/triage',
  getParentRoute: () => AppRoute,
} as any)
const AppSupervisionRoute = AppSupervisionRouteImport.update({
  id: '/supervision',
  path: '/supervision',
  getParentRoute: () => AppRoute,
} as any)
const AppSlaCenterRoute = AppSlaCenterRouteImport.update({
  id: '/sla-center',
  path: '/sla-center',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppQueueRoute = AppQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppNewRoute = AppNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppRoute,
} as any)
const AppMyTicketsRoute = AppMyTicketsRouteImport.update({
  id: '/my-tickets',
  path: '/my-tickets',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppDirectionRoute = AppDirectionRouteImport.update({
  id: '/direction',
  path: '/direction',
  getParentRoute: () => AppRoute,
} as any)
const AppDgRoute = AppDgRouteImport.update({
  id: '/dg',
  path: '/dg',
  getParentRoute: () => AppRoute,
} as any)
const AppChiefInboxRoute = AppChiefInboxRouteImport.update({
  id: '/chief-inbox',
  path: '/chief-inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestsIndexRoute = AppRequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestsHistoryRoute = AppRequestsHistoryRouteImport.update({
  id: '/requests/history',
  path: '/requests/history',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestsIdRoute = AppRequestsIdRouteImport.update({
  id: '/requests/$id',
  path: '/requests/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminUnitsRoute = AppAdminUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminSlaRoute = AppAdminSlaRouteImport.update({
  id: '/sla',
  path: '/sla',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminSecurityRoute = AppAdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminRoutingRoute = AppAdminRoutingRouteImport.update({
  id: '/routing',
  path: '/routing',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminReferencesRoute = AppAdminReferencesRouteImport.update({
  id: '/references',
  path: '/references',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminPrioritiesRoute = AppAdminPrioritiesRouteImport.update({
  id: '/priorities',
  path: '/priorities',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminOrgRoute = AppAdminOrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminLogsRoute = AppAdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminKnowledgeRoute = AppAdminKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminHomepageRoute = AppAdminHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminDirectionsRoute = AppAdminDirectionsRouteImport.update({
  id: '/directions',
  path: '/directions',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminCommunicationRoute = AppAdminCommunicationRouteImport.update({
  id: '/communication',
  path: '/communication',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAuditRoute = AppAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/app': typeof AppRouteWithChildren
  '/create-request': typeof CreateRequestRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/track': typeof TrackRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/chief-inbox': typeof AppChiefInboxRoute
  '/app/dg': typeof AppDgRoute
  '/app/direction': typeof AppDirectionRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/my-tickets': typeof AppMyTicketsRoute
  '/app/new': typeof AppNewRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/queue': typeof AppQueueRoute
  '/app/reports': typeof AppReportsRoute
  '/app/sla-center': typeof AppSlaCenterRoute
  '/app/supervision': typeof AppSupervisionRoute
  '/app/triage': typeof AppTriageRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/audit': typeof AppAdminAuditRoute
  '/app/admin/communication': typeof AppAdminCommunicationRoute
  '/app/admin/directions': typeof AppAdminDirectionsRoute
  '/app/admin/homepage': typeof AppAdminHomepageRoute
  '/app/admin/knowledge': typeof AppAdminKnowledgeRoute
  '/app/admin/logs': typeof AppAdminLogsRoute
  '/app/admin/org': typeof AppAdminOrgRoute
  '/app/admin/priorities': typeof AppAdminPrioritiesRoute
  '/app/admin/references': typeof AppAdminReferencesRoute
  '/app/admin/routing': typeof AppAdminRoutingRoute
  '/app/admin/security': typeof AppAdminSecurityRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/admin/sla': typeof AppAdminSlaRoute
  '/app/admin/units': typeof AppAdminUnitsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/requests/$id': typeof AppRequestsIdRoute
  '/app/requests/history': typeof AppRequestsHistoryRoute
  '/app/requests/': typeof AppRequestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/create-request': typeof CreateRequestRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/track': typeof TrackRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/chief-inbox': typeof AppChiefInboxRoute
  '/app/dg': typeof AppDgRoute
  '/app/direction': typeof AppDirectionRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/my-tickets': typeof AppMyTicketsRoute
  '/app/new': typeof AppNewRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/queue': typeof AppQueueRoute
  '/app/reports': typeof AppReportsRoute
  '/app/sla-center': typeof AppSlaCenterRoute
  '/app/supervision': typeof AppSupervisionRoute
  '/app/triage': typeof AppTriageRoute
  '/app': typeof AppIndexRoute
  '/app/admin/audit': typeof AppAdminAuditRoute
  '/app/admin/communication': typeof AppAdminCommunicationRoute
  '/app/admin/directions': typeof AppAdminDirectionsRoute
  '/app/admin/homepage': typeof AppAdminHomepageRoute
  '/app/admin/knowledge': typeof AppAdminKnowledgeRoute
  '/app/admin/logs': typeof AppAdminLogsRoute
  '/app/admin/org': typeof AppAdminOrgRoute
  '/app/admin/priorities': typeof AppAdminPrioritiesRoute
  '/app/admin/references': typeof AppAdminReferencesRoute
  '/app/admin/routing': typeof AppAdminRoutingRoute
  '/app/admin/security': typeof AppAdminSecurityRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/admin/sla': typeof AppAdminSlaRoute
  '/app/admin/units': typeof AppAdminUnitsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/requests/$id': typeof AppRequestsIdRoute
  '/app/requests/history': typeof AppRequestsHistoryRoute
  '/app/requests': typeof AppRequestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/app': typeof AppRouteWithChildren
  '/create-request': typeof CreateRequestRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/track': typeof TrackRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/chief-inbox': typeof AppChiefInboxRoute
  '/app/dg': typeof AppDgRoute
  '/app/direction': typeof AppDirectionRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/my-tickets': typeof AppMyTicketsRoute
  '/app/new': typeof AppNewRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/queue': typeof AppQueueRoute
  '/app/reports': typeof AppReportsRoute
  '/app/sla-center': typeof AppSlaCenterRoute
  '/app/supervision': typeof AppSupervisionRoute
  '/app/triage': typeof AppTriageRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/audit': typeof AppAdminAuditRoute
  '/app/admin/communication': typeof AppAdminCommunicationRoute
  '/app/admin/directions': typeof AppAdminDirectionsRoute
  '/app/admin/homepage': typeof AppAdminHomepageRoute
  '/app/admin/knowledge': typeof AppAdminKnowledgeRoute
  '/app/admin/logs': typeof AppAdminLogsRoute
  '/app/admin/org': typeof AppAdminOrgRoute
  '/app/admin/priorities': typeof AppAdminPrioritiesRoute
  '/app/admin/references': typeof AppAdminReferencesRoute
  '/app/admin/routing': typeof AppAdminRoutingRoute
  '/app/admin/security': typeof AppAdminSecurityRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/admin/sla': typeof AppAdminSlaRoute
  '/app/admin/units': typeof AppAdminUnitsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/requests/$id': typeof AppRequestsIdRoute
  '/app/requests/history': typeof AppRequestsHistoryRoute
  '/app/requests/': typeof AppRequestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-login'
    | '/app'
    | '/create-request'
    | '/forgot-password'
    | '/help'
    | '/knowledge'
    | '/login'
    | '/register'
    | '/track'
    | '/app/admin'
    | '/app/chief-inbox'
    | '/app/dg'
    | '/app/direction'
    | '/app/knowledge'
    | '/app/my-tickets'
    | '/app/new'
    | '/app/notifications'
    | '/app/profile'
    | '/app/queue'
    | '/app/reports'
    | '/app/sla-center'
    | '/app/supervision'
    | '/app/triage'
    | '/app/'
    | '/app/admin/audit'
    | '/app/admin/communication'
    | '/app/admin/directions'
    | '/app/admin/homepage'
    | '/app/admin/knowledge'
    | '/app/admin/logs'
    | '/app/admin/org'
    | '/app/admin/priorities'
    | '/app/admin/references'
    | '/app/admin/routing'
    | '/app/admin/security'
    | '/app/admin/settings'
    | '/app/admin/sla'
    | '/app/admin/units'
    | '/app/admin/users'
    | '/app/requests/$id'
    | '/app/requests/history'
    | '/app/requests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/create-request'
    | '/forgot-password'
    | '/help'
    | '/knowledge'
    | '/login'
    | '/register'
    | '/track'
    | '/app/admin'
    | '/app/chief-inbox'
    | '/app/dg'
    | '/app/direction'
    | '/app/knowledge'
    | '/app/my-tickets'
    | '/app/new'
    | '/app/notifications'
    | '/app/profile'
    | '/app/queue'
    | '/app/reports'
    | '/app/sla-center'
    | '/app/supervision'
    | '/app/triage'
    | '/app'
    | '/app/admin/audit'
    | '/app/admin/communication'
    | '/app/admin/directions'
    | '/app/admin/homepage'
    | '/app/admin/knowledge'
    | '/app/admin/logs'
    | '/app/admin/org'
    | '/app/admin/priorities'
    | '/app/admin/references'
    | '/app/admin/routing'
    | '/app/admin/security'
    | '/app/admin/settings'
    | '/app/admin/sla'
    | '/app/admin/units'
    | '/app/admin/users'
    | '/app/requests/$id'
    | '/app/requests/history'
    | '/app/requests'
  id:
    | '__root__'
    | '/'
    | '/admin-login'
    | '/app'
    | '/create-request'
    | '/forgot-password'
    | '/help'
    | '/knowledge'
    | '/login'
    | '/register'
    | '/track'
    | '/app/admin'
    | '/app/chief-inbox'
    | '/app/dg'
    | '/app/direction'
    | '/app/knowledge'
    | '/app/my-tickets'
    | '/app/new'
    | '/app/notifications'
    | '/app/profile'
    | '/app/queue'
    | '/app/reports'
    | '/app/sla-center'
    | '/app/supervision'
    | '/app/triage'
    | '/app/'
    | '/app/admin/audit'
    | '/app/admin/communication'
    | '/app/admin/directions'
    | '/app/admin/homepage'
    | '/app/admin/knowledge'
    | '/app/admin/logs'
    | '/app/admin/org'
    | '/app/admin/priorities'
    | '/app/admin/references'
    | '/app/admin/routing'
    | '/app/admin/security'
    | '/app/admin/settings'
    | '/app/admin/sla'
    | '/app/admin/units'
    | '/app/admin/users'
    | '/app/requests/$id'
    | '/app/requests/history'
    | '/app/requests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AppRoute: typeof AppRouteWithChildren
  CreateRequestRoute: typeof CreateRequestRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  KnowledgeRoute: typeof KnowledgeRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  TrackRoute: typeof TrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-request': {
      id: '/create-request'
      path: '/create-request'
      fullPath: '/create-request'
      preLoaderRoute: typeof CreateRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/triage': {
      id: '/app/triage'
      path: '/triage'
      fullPath: '/app/triage'
      preLoaderRoute: typeof AppTriageRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/supervision': {
      id: '/app/supervision'
      path: '/supervision'
      fullPath: '/app/supervision'
      preLoaderRoute: typeof AppSupervisionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sla-center': {
      id: '/app/sla-center'
      path: '/sla-center'
      fullPath: '/app/sla-center'
      preLoaderRoute: typeof AppSlaCenterRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/queue': {
      id: '/app/queue'
      path: '/queue'
      fullPath: '/app/queue'
      preLoaderRoute: typeof AppQueueRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/new': {
      id: '/app/new'
      path: '/new'
      fullPath: '/app/new'
      preLoaderRoute: typeof AppNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/my-tickets': {
      id: '/app/my-tickets'
      path: '/my-tickets'
      fullPath: '/app/my-tickets'
      preLoaderRoute: typeof AppMyTicketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/knowledge': {
      id: '/app/knowledge'
      path: '/knowledge'
      fullPath: '/app/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/direction': {
      id: '/app/direction'
      path: '/direction'
      fullPath: '/app/direction'
      preLoaderRoute: typeof AppDirectionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dg': {
      id: '/app/dg'
      path: '/dg'
      fullPath: '/app/dg'
      preLoaderRoute: typeof AppDgRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chief-inbox': {
      id: '/app/chief-inbox'
      path: '/chief-inbox'
      fullPath: '/app/chief-inbox'
      preLoaderRoute: typeof AppChiefInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/requests/': {
      id: '/app/requests/'
      path: '/requests'
      fullPath: '/app/requests/'
      preLoaderRoute: typeof AppRequestsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/requests/history': {
      id: '/app/requests/history'
      path: '/requests/history'
      fullPath: '/app/requests/history'
      preLoaderRoute: typeof AppRequestsHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/requests/$id': {
      id: '/app/requests/$id'
      path: '/requests/$id'
      fullPath: '/app/requests/$id'
      preLoaderRoute: typeof AppRequestsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/units': {
      id: '/app/admin/units'
      path: '/units'
      fullPath: '/app/admin/units'
      preLoaderRoute: typeof AppAdminUnitsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/sla': {
      id: '/app/admin/sla'
      path: '/sla'
      fullPath: '/app/admin/sla'
      preLoaderRoute: typeof AppAdminSlaRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/settings': {
      id: '/app/admin/settings'
      path: '/settings'
      fullPath: '/app/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/security': {
      id: '/app/admin/security'
      path: '/security'
      fullPath: '/app/admin/security'
      preLoaderRoute: typeof AppAdminSecurityRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/routing': {
      id: '/app/admin/routing'
      path: '/routing'
      fullPath: '/app/admin/routing'
      preLoaderRoute: typeof AppAdminRoutingRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/references': {
      id: '/app/admin/references'
      path: '/references'
      fullPath: '/app/admin/references'
      preLoaderRoute: typeof AppAdminReferencesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/priorities': {
      id: '/app/admin/priorities'
      path: '/priorities'
      fullPath: '/app/admin/priorities'
      preLoaderRoute: typeof AppAdminPrioritiesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/org': {
      id: '/app/admin/org'
      path: '/org'
      fullPath: '/app/admin/org'
      preLoaderRoute: typeof AppAdminOrgRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/logs': {
      id: '/app/admin/logs'
      path: '/logs'
      fullPath: '/app/admin/logs'
      preLoaderRoute: typeof AppAdminLogsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/knowledge': {
      id: '/app/admin/knowledge'
      path: '/knowledge'
      fullPath: '/app/admin/knowledge'
      preLoaderRoute: typeof AppAdminKnowledgeRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/homepage': {
      id: '/app/admin/homepage'
      path: '/homepage'
      fullPath: '/app/admin/homepage'
      preLoaderRoute: typeof AppAdminHomepageRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/directions': {
      id: '/app/admin/directions'
      path: '/directions'
      fullPath: '/app/admin/directions'
      preLoaderRoute: typeof AppAdminDirectionsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/communication': {
      id: '/app/admin/communication'
      path: '/communication'
      fullPath: '/app/admin/communication'
      preLoaderRoute: typeof AppAdminCommunicationRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/audit': {
      id: '/app/admin/audit'
      path: '/audit'
      fullPath: '/app/admin/audit'
      preLoaderRoute: typeof AppAdminAuditRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminAuditRoute: typeof AppAdminAuditRoute
  AppAdminCommunicationRoute: typeof AppAdminCommunicationRoute
  AppAdminDirectionsRoute: typeof AppAdminDirectionsRoute
  AppAdminHomepageRoute: typeof AppAdminHomepageRoute
  AppAdminKnowledgeRoute: typeof AppAdminKnowledgeRoute
  AppAdminLogsRoute: typeof AppAdminLogsRoute
  AppAdminOrgRoute: typeof AppAdminOrgRoute
  AppAdminPrioritiesRoute: typeof AppAdminPrioritiesRoute
  AppAdminReferencesRoute: typeof AppAdminReferencesRoute
  AppAdminRoutingRoute: typeof AppAdminRoutingRoute
  AppAdminSecurityRoute: typeof AppAdminSecurityRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppAdminSlaRoute: typeof AppAdminSlaRoute
  AppAdminUnitsRoute: typeof AppAdminUnitsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAuditRoute: AppAdminAuditRoute,
  AppAdminCommunicationRoute: AppAdminCommunicationRoute,
  AppAdminDirectionsRoute: AppAdminDirectionsRoute,
  AppAdminHomepageRoute: AppAdminHomepageRoute,
  AppAdminKnowledgeRoute: AppAdminKnowledgeRoute,
  AppAdminLogsRoute: AppAdminLogsRoute,
  AppAdminOrgRoute: AppAdminOrgRoute,
  AppAdminPrioritiesRoute: AppAdminPrioritiesRoute,
  AppAdminReferencesRoute: AppAdminReferencesRoute,
  AppAdminRoutingRoute: AppAdminRoutingRoute,
  AppAdminSecurityRoute: AppAdminSecurityRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppAdminSlaRoute: AppAdminSlaRoute,
  AppAdminUnitsRoute: AppAdminUnitsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppChiefInboxRoute: typeof AppChiefInboxRoute
  AppDgRoute: typeof AppDgRoute
  AppDirectionRoute: typeof AppDirectionRoute
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppMyTicketsRoute: typeof AppMyTicketsRoute
  AppNewRoute: typeof AppNewRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppQueueRoute: typeof AppQueueRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSlaCenterRoute: typeof AppSlaCenterRoute
  AppSupervisionRoute: typeof AppSupervisionRoute
  AppTriageRoute: typeof AppTriageRoute
  AppIndexRoute: typeof AppIndexRoute
  AppRequestsIdRoute: typeof AppRequestsIdRoute
  AppRequestsHistoryRoute: typeof AppRequestsHistoryRoute
  AppRequestsIndexRoute: typeof AppRequestsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppChiefInboxRoute: AppChiefInboxRoute,
  AppDgRoute: AppDgRoute,
  AppDirectionRoute: AppDirectionRoute,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppMyTicketsRoute: AppMyTicketsRoute,
  AppNewRoute: AppNewRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppQueueRoute: AppQueueRoute,
  AppReportsRoute: AppReportsRoute,
  AppSlaCenterRoute: AppSlaCenterRoute,
  AppSupervisionRoute: AppSupervisionRoute,
  AppTriageRoute: AppTriageRoute,
  AppIndexRoute: AppIndexRoute,
  AppRequestsIdRoute: AppRequestsIdRoute,
  AppRequestsHistoryRoute: AppRequestsHistoryRoute,
  AppRequestsIndexRoute: AppRequestsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminLoginRoute: AdminLoginRoute,
  AppRoute: AppRouteWithChildren,
  CreateRequestRoute: CreateRequestRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  KnowledgeRoute: KnowledgeRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  TrackRoute: TrackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
